# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170523_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
